export const stocks = [
    {
      ID: 1,
      "Stock Name": "Reliance Industries",
      Symbol: "RELIANCE",
      "Market Cap (in ₹ Crores)": 1500000,
      "Percentage Change (%)": 2.0,
    },
    {
      ID: 2,
      "Stock Name": "Tata Consultancy Services",
      Symbol: "TCS",
      "Market Cap (in ₹ Crores)": 1200000,
      "Percentage Change (%)": 0.75,
    },
    {
      ID: 3,
      "Stock Name": "Infosys",
      Symbol: "INFY",
      "Market Cap (in ₹ Crores)": 700000,
      "Percentage Change (%)": -0.5,
    },
    {
      ID: 4,
      "Stock Name": "HDFC Bank",
      Symbol: "HDFCBANK",
      "Market Cap (in ₹ Crores)": 800000,
      "Percentage Change (%)": 2.0,
    },
    {
      ID: 5,
      "Stock Name": "Hindustan Unilever",
      Symbol: "HINDUNILVR",
      "Market Cap (in ₹ Crores)": 600000,
      "Percentage Change (%)": 0.9,
    },
    {
      ID: 6,
      "Stock Name": "ICICI Bank",
      Symbol: "ICICIBANK",
      "Market Cap (in ₹ Crores)": 500000,
      "Percentage Change (%)": -1.2,
    },
    {
      ID: 7,
      "Stock Name": "State Bank of India",
      Symbol: "SBIN",
      "Market Cap (in ₹ Crores)": 400000,
      "Percentage Change (%)": 1.1,
    },
    {
      ID: 8,
      "Stock Name": "Bharti Airtel",
      Symbol: "BHARTIARTL",
      "Market Cap (in ₹ Crores)": 300000,
      "Percentage Change (%)": 0.8,
    },
    {
      ID: 9,
      "Stock Name": "Maruti Suzuki",
      Symbol: "MARUTI",
      "Market Cap (in ₹ Crores)": 350000,
      "Percentage Change (%)": -0.3,
    },
    {
      ID: 10,
      "Stock Name": "Larsen & Toubro",
      Symbol: "L&T",
      "Market Cap (in ₹ Crores)": 450000,
      "Percentage Change (%)": 1.5,
    },
    {
      ID: 11,
      "Stock Name": "Axis Bank",
      Symbol: "AXISBANK",
      "Market Cap (in ₹ Crores)": 290000,
      "Percentage Change (%)": 0.4,
    },
    {
      ID: 12,
      "Stock Name": "Kotak Mahindra Bank",
      Symbol: "KOTAKBANK",
      "Market Cap (in ₹ Crores)": 320000,
      "Percentage Change (%)": 1.1,
    },
    {
      ID: 13,
      "Stock Name": "Wipro",
      Symbol: "WIPRO",
      "Market Cap (in ₹ Crores)": 260000,
      "Percentage Change (%)": -0.6,
    },
    {
      ID: 14,
      "Stock Name": "SBI Life Insurance",
      Symbol: "SBILIFE",
      "Market Cap (in ₹ Crores)": 210000,
      "Percentage Change (%)": 2.0,
    },
    {
      ID: 15,
      "Stock Name": "HCL Technologies",
      Symbol: "HCLTECH",
      "Market Cap (in ₹ Crores)": 300000,
      "Percentage Change (%)": 0.7,
    },
    {
      ID: 16,
      "Stock Name": "Tata Steel",
      Symbol: "TATASTEEL",
      "Market Cap (in ₹ Crores)": 400000,
      "Percentage Change (%)": -1.0,
    },
    {
      ID: 17,
      "Stock Name": "Sun Pharmaceutical",
      Symbol: "SUNPHARMA",
      "Market Cap (in ₹ Crores)": 350000,
      "Percentage Change (%)": 0.5,
    },
    {
      ID: 18,
      "Stock Name": "Bajaj Finance",
      Symbol: "BAJFINANCE",
      "Market Cap (in ₹ Crores)": 600000,
      "Percentage Change (%)": 1.3,
    },
    {
      ID: 19,
      "Stock Name": "Asian Paints",
      Symbol: "ASIANPAINT",
      "Market Cap (in ₹ Crores)": 650000,
      "Percentage Change (%)": 0.6,
    },
    {
      ID: 20,
      "Stock Name": "Tech Mahindra",
      Symbol: "TECHM",
      "Market Cap (in ₹ Crores)": 250000,
      "Percentage Change (%)": 1.2,
    },
    {
      ID: 21,
      "Stock Name": "Hero MotoCorp",
      Symbol: "HEROMOTOCO",
      "Market Cap (in ₹ Crores)": 420000,
      "Percentage Change (%)": -0.9,
    },
    {
      ID: 22,
      "Stock Name": "GAIL India",
      Symbol: "GAIL",
      "Market Cap (in ₹ Crores)": 180000,
      "Percentage Change (%)": 0.2,
    },
    {
      ID: 23,
      "Stock Name": "Tata Motors",
      Symbol: "TATAMOTORS",
      "Market Cap (in ₹ Crores)": 500000,
      "Percentage Change (%)": 2.0,
    },
    {
      ID: 24,
      "Stock Name": "Cipla",
      Symbol: "CIPLA",
      "Market Cap (in ₹ Crores)": 330000,
      "Percentage Change (%)": 1.7,
    },
    {
      ID: 25,
      "Stock Name": "Minda Industries",
      Symbol: "MINDAIND",
      "Market Cap (in ₹ Crores)": 150000,
      "Percentage Change (%)": 1.4,
    },
    {
      ID: 26,
      "Stock Name": "UPL Limited",
      Symbol: "UPL",
      "Market Cap (in ₹ Crores)": 240000,
      "Percentage Change (%)": 2.0,
    },
  ];